# Generated by Django 3.0.1 on 2021-12-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211207_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='score',
        ),
    ]
